#!/usr/bin/env bash
# mesh-nightly-synthesize.sh — 04:00 UTC cron: synthesize individual reflections.
#
# Reads EVENTS/chatroom-nightly-reflection-<date>/ev-*.md (skipping SYNTHESIS:true),
# detects absentees against mesh/REGISTRY, writes dead-letter notes for them,
# publishes one SYNTHESIS:true event on the same topic, then writes
# BLACKBOARD/nightly-reflections/<date>/group.md and bumps LATEST.md.
#
# Per josh's accepted output spec + src's synthesis flow.

set -euo pipefail

MESH_ROOT="${MESH_ROOT:-/opt/filament-mesh}"
export MESH_ROOT
export AGENT_URI="${AGENT_URI:-host@mesh}"

LOG="${MESH_ROOT}/logs/mesh-nightly-synthesize.log"
mkdir -p "$(dirname "$LOG")"
log() { printf '%s %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >> "$LOG"; }

DATE="${1:-$(date -u +%Y-%m-%d)}"
TOPIC="chatroom.nightly-reflection-${DATE}"
TOPIC_SLUG="chatroom-nightly-reflection-${DATE}"
TOPIC_DIR="${MESH_ROOT}/mesh/EVENTS/${TOPIC_SLUG}"

BLACKBOARD_DIR="${MESH_ROOT}/mesh/BLACKBOARD/nightly-reflections/${DATE}"
LATEST="${MESH_ROOT}/mesh/BLACKBOARD/nightly-reflections/LATEST.md"

BIN_DIR="$(cd "$(dirname "$0")/.." && pwd)/bin"
MESH_EVENT="${BIN_DIR}/mesh-event"

if [[ ! -d "$TOPIC_DIR" ]]; then
    log "no topic dir (${TOPIC_DIR}); nothing to synthesize"
    exit 0
fi

log "synthesize start — date=${DATE}"

mkdir -p "$BLACKBOARD_DIR"

# ── 1. Collect reflection events (skip synthesis posts + validate AUTHOR) ──
# Validation per josh's REFLECTION-PROTOCOL.md §Phase 3:
#   - AUTHOR must be a registered agent (agents/<name>/ slot exists)
#   - AUTHOR must be in this topic's subscribers/ (i.e. was invited at kickoff)
# Forged reflections from non-subscribed agents are quarantined, not synthesized.
SUBS_DIR="${TOPIC_DIR}/subscribers"
AGENTS_DIR="${MESH_ROOT}/agents"
QUARANTINE_DIR="${MESH_ROOT}/mesh/QUARANTINE"
mkdir -p "$QUARANTINE_DIR"

declare -a REFL_FILES=()
for f in "${TOPIC_DIR}"/ev-*.md; do
    [[ -f "$f" ]] || continue
    if grep -q '^SYNTHESIS: true' "$f" 2>/dev/null; then continue; fi

    author="$(awk -F': ' '/^AUTHOR:/ {gsub(/@mesh/,"",$2); gsub(/[[:space:]]/,"",$2); print $2; exit}' "$f")"
    if [[ -z "$author" ]]; then
        log "QUARANTINE $(basename "$f") — missing AUTHOR"
        cp "$f" "${QUARANTINE_DIR}/$(basename "$f" .md)-no-author.md"
        continue
    fi
    if [[ ! -d "${AGENTS_DIR}/${author}" ]]; then
        log "QUARANTINE $(basename "$f") — unknown AUTHOR '${author}' (no agents/ slot)"
        cp "$f" "${QUARANTINE_DIR}/$(basename "$f" .md)-unknown-author.md"
        continue
    fi
    if [[ ! -f "${SUBS_DIR}/${author}" ]]; then
        log "QUARANTINE $(basename "$f") — AUTHOR '${author}' not subscribed to topic"
        cp "$f" "${QUARANTINE_DIR}/$(basename "$f" .md)-unsubscribed-author.md"
        continue
    fi

    REFL_FILES+=("$f")
done

# ── 2. Who posted? Who is absent? ────────────────────────────────────────────
declare -a POSTED=()
for f in "${REFL_FILES[@]}"; do
    a="$(awk -F': ' '/^AUTHOR:/ {gsub(/@mesh/,"",$2); gsub(/[[:space:]]/,"",$2); print $2; exit}' "$f")"
    [[ -n "$a" ]] && POSTED+=("$a")
done

declare -a ABSENT=()
for reg in "${MESH_ROOT}/mesh/REGISTRY/"*.md; do
    [[ -f "$reg" ]] || continue
    agent="$(basename "$reg" .md)"
    case "$agent" in
        host|REGISTRY|"") continue ;;
    esac
    if ! printf '%s\n' "${POSTED[@]}" | grep -qx "$agent"; then
        ABSENT+=("$agent")
    fi
done

# ── 3. Dead-letter absentees (audit trail; no retry) ─────────────────────────
for a in "${ABSENT[@]}"; do
    dl_dir="${MESH_ROOT}/mesh/DEAD_LETTER/${a}"
    mkdir -p "$dl_dir"
    ts="$(date -u +%s)"
    cat > "${dl_dir}/${ts}-nightly-miss-${DATE}.md" <<BODY
---
KIND: dead-letter
AUTHOR: host@mesh
REASON: absent-from-nightly-reflection
DATE: ${DATE}
---
${a}@mesh did not post a reflection to ${TOPIC} by the 04:00Z synthesis cutoff.
No retry; next cron fires tomorrow at 03:15Z.
BODY
done

# ── 4. Per-agent BLACKBOARD files + group.md ─────────────────────────────────
for f in "${REFL_FILES[@]}"; do
    a="$(awk -F': ' '/^AUTHOR:/ {gsub(/@mesh/,"",$2); gsub(/[[:space:]]/,"",$2); print $2; exit}' "$f")"
    [[ -n "$a" ]] || continue
    # Strip frontmatter for the BLACKBOARD copy
    awk 'NR==1 && /^---$/ {fm=1; next} fm==1 && /^---$/ {fm=0; next} fm!=1' "$f" \
        > "${BLACKBOARD_DIR}/${a}.md"
done

GROUP="${BLACKBOARD_DIR}/group.md"
{
    echo "# Nightly synthesis — ${DATE}"
    echo
    echo "_Generated by mesh-nightly-synthesize.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
    echo
    if [[ ${#ABSENT[@]} -gt 0 ]]; then
        printf '## Absent\n\n'
        for a in "${ABSENT[@]}"; do printf -- '- %s@mesh\n' "$a"; done
        echo
    else
        echo "## Absent"
        echo
        echo "_none — full attendance._"
        echo
    fi
    echo "## Reflections"
    echo
    for f in "${REFL_FILES[@]}"; do
        a="$(awk -F': ' '/^AUTHOR:/ {gsub(/@mesh/,"",$2); gsub(/[[:space:]]/,"",$2); print $2; exit}' "$f")"
        pub="$(awk -F': ' '/^PUBLISHED_AT:/ {gsub(/[[:space:]]/,"",$2); print $2; exit}' "$f")"
        echo "### ${a}@mesh  (${pub})"
        echo
        awk 'NR==1 && /^---$/ {fm=1; next} fm==1 && /^---$/ {fm=0; next} fm!=1' "$f"
        echo
    done
} > "$GROUP"

# LATEST.md pointer (atomic)
tmp_latest="${LATEST}.tmp"
{
    echo "# LATEST nightly reflection"
    echo
    echo "- Date: ${DATE}"
    echo "- Group synthesis: BLACKBOARD/nightly-reflections/${DATE}/group.md"
    echo "- Individual files: BLACKBOARD/nightly-reflections/${DATE}/<agent>.md"
    echo "- Topic: ${TOPIC}"
    echo "- Absent: ${ABSENT[*]:-none}"
    echo "- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$tmp_latest"
mv "$tmp_latest" "$LATEST"

# ── 5. Publish SYNTHESIS event back to the topic (one-line pointer) ──────────
synth_body="$(cat <<BODY
# Synthesis — ${DATE}

- Reflections: ${#REFL_FILES[@]}
- Absent: ${ABSENT[*]:-none}
- Full synthesis: mesh/BLACKBOARD/nightly-reflections/${DATE}/group.md
- LATEST pointer: mesh/BLACKBOARD/nightly-reflections/LATEST.md
BODY
)"

# Synthesis post is not --chat (fanout should be normal announcement) BUT we add
# SYNTHESIS:true to the event body so the event file is tagged. Use --body for
# atomic publish; avoid re-using --chat so consumers can filter on KIND + SYNTHESIS.
if ! printf 'SYNTHESIS: true\n\n%s\n' "$synth_body" \
   | timeout 60 "$MESH_EVENT" publish "$TOPIC" --ttl 604800 >>"$LOG" 2>&1; then
    log "WARN synthesis publish failed (blackboard still written)"
fi

log "synthesize done — posts=${#REFL_FILES[@]} absent=${#ABSENT[@]}"
