#!/usr/bin/env bash
# mesh-blocker-check.sh — periodic SLA sweep for KIND:blocker messages.
#
# Scans every agent inbox for KIND:blocker files past their declared SLA,
# emits STATE_CHECK alerts for the host, and rewrites a live snapshot at
# BLACKBOARD/blockers/OPEN.md showing all currently-open blockers.
#
# Closes the "blocker filed, host doesn't notice" pattern. Designed to run
# on a 15-minute timer.
#
# Configuration (all overridable via env):
#   MESH_ROOT     mesh root (default: /opt/filament-mesh)
#   LOG_DIR       log directory (default: /var/log/filament)
#   DEFAULT_SLA   minutes if SLA_MINUTES header is missing (default: 30)

set -euo pipefail

MESH_ROOT="${MESH_ROOT:-/opt/filament-mesh}"
LOG_DIR="${LOG_DIR:-/var/log/filament}"
DEFAULT_SLA="${DEFAULT_SLA:-30}"

LOG="${LOG_DIR}/mesh-blocker-check.log"
OPEN_FILE="${MESH_ROOT}/mesh/BLACKBOARD/blockers/OPEN.md"
STATE_CHECK_DIR="${MESH_ROOT}/mesh/STATE_CHECK"

mkdir -p "$(dirname "$OPEN_FILE")" "$LOG_DIR" "$STATE_CHECK_DIR"
NOW=$(date +%s)

log() { echo "$(date -uIs) $*" >> "$LOG"; }

# Reset OPEN.md as a snapshot — only currently-open blockers shown
cat > "$OPEN_FILE.tmp" <<HDR
# Open Blockers — host live snapshot
# Last regenerated: $(date -uIs)
# Generated by: filament/scripts/mesh-blocker-check.sh
HDR

OPEN_COUNT=0
ESCALATED=0

for inbox_dir in "${MESH_ROOT}"/agents/*/inbox; do
    [[ -d "$inbox_dir" ]] || continue
    agent="$(basename "$(dirname "$inbox_dir")")"

    for msg in "$inbox_dir"/*.md; do
        [[ -f "$msg" ]] || continue
        head -10 "$msg" | grep -q "^KIND: blocker" || continue

        # `|| true`: grep exits 1 when the header is absent, and under `set -euo pipefail`
        # that killed the whole sweep SILENTLY (rc=1, zero output) the moment any KIND:blocker
        # message arrived WITHOUT an SLA_MINUTES header — which is the exact case the
        # DEFAULT_SLA on the next line exists to handle. The fallback was already correct; it
        # simply never ran. (Line 55 below already uses `|| basename`, same pattern.)
        # Measured 2026-08-30: 3 blocker messages without the header took this cron down.
        sla=$(grep -m1 '^SLA_MINUTES:' "$msg" | awk '{print $2}' || true)
        sla=${sla:-$DEFAULT_SLA}
        mtime=$(stat -c %Y "$msg")
        age_min=$(( (NOW - mtime) / 60 ))

        OPEN_COUNT=$((OPEN_COUNT + 1))
        subject=$(grep -m1 '^SUBJECT:' "$msg" | sed 's/^SUBJECT: *//' || basename "$msg")

        echo "" >> "$OPEN_FILE.tmp"
        echo "## ${agent}: $(basename "$msg")" >> "$OPEN_FILE.tmp"
        echo "- age: ${age_min} min  ·  SLA: ${sla} min  ·  status: $([[ $age_min -gt $sla ]] && echo OVER-SLA || echo within-SLA)" >> "$OPEN_FILE.tmp"
        echo "- subject: ${subject}" >> "$OPEN_FILE.tmp"
        grep -E '^(BLOCKED_ON|BLOCKER_TYPE|BLOCKS|RESOLUTION_PATHS|UNBLOCKS):' "$msg" | sed 's/^/- /' >> "$OPEN_FILE.tmp" || true

        if [[ $age_min -gt $sla ]]; then
            ESCALATED=$((ESCALATED + 1))
            stamp="${STATE_CHECK_DIR}/$(date +%s)-host-blocker-${agent}-overdue.md"
            cat > "$stamp" <<SC
---
KIND: state-check
EVENT: blocker-overdue
AGENT_AFFECTED: ${agent}
ORIGINATING_FILE: $(basename "$msg")
AGE_MINUTES: ${age_min}
SLA_MINUTES: ${sla}
TIMESTAMP: $(date -uIs)
---
Blocker from ${agent} has been open for ${age_min} min (SLA: ${sla}). Host action required.
SC
            log "ESCALATED: ${agent}/$(basename "$msg") age=${age_min}min sla=${sla}min"
        fi
    done
done

mv "$OPEN_FILE.tmp" "$OPEN_FILE"
log "sweep: ${OPEN_COUNT} open  ${ESCALATED} escalated"
